# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"conv": "01_utils.ipynb",
         "conv2d": "01_utils.ipynb",
         "batch_conv2d": "01_utils.ipynb",
         "dilute": "01_utils.ipynb",
         "randn": "01_utils.ipynb",
         "rand": "01_utils.ipynb",
         "argmax2d": "01_utils.ipynb",
         "argmin2d": "01_utils.ipynb",
         "float_mask": "01_utils.ipynb",
         "not_": "01_utils.ipynb",
         "or_": "01_utils.ipynb",
         "and_": "01_utils.ipynb",
         "xor_": "01_utils.ipynb",
         "where_": "01_utils.ipynb",
         "show_mask": "02_brushes.ipynb",
         "circular_brush": "02_brushes.ipynb",
         "notched_square_brush": "02_brushes.ipynb",
         "UNASSIGNED": "03_design.ipynb",
         "VOID": "03_design.ipynb",
         "SOLID": "03_design.ipynb",
         "PIXEL_IMPOSSIBLE": "03_design.ipynb",
         "PIXEL_EXISTING": "03_design.ipynb",
         "PIXEL_POSSIBLE": "03_design.ipynb",
         "PIXEL_REQUIRED": "03_design.ipynb",
         "TOUCH_REQUIRED": "03_design.ipynb",
         "TOUCH_INVALID": "03_design.ipynb",
         "TOUCH_EXISTING": "03_design.ipynb",
         "TOUCH_VALID": "03_design.ipynb",
         "TOUCH_FREE": "03_design.ipynb",
         "TOUCH_RESOLVING": "03_design.ipynb",
         "Design": "03_design.ipynb",
         "new_design": "03_design.ipynb",
         "design_mask": "03_design.ipynb",
         "visualize": "03_design.ipynb",
         "add_void_touch": "04_touching.ipynb",
         "take_free_void_touches": "04_touching.ipynb",
         "add_solid_touch": "04_touching.ipynb",
         "take_free_solid_touches": "04_touching.ipynb",
         "new_latent_design": "05_conditional_generator.ipynb",
         "transform": "05_conditional_generator.ipynb",
         "conditional_algirithm_step": "05_conditional_generator.ipynb",
         "conditional_generator": "05_conditional_generator.ipynb",
         "generate_feasible_design": "05_conditional_generator.ipynb",
         "generate_feasible_design_mask_": "05_conditional_generator.ipynb",
         "generate_feasible_design_mask": "05_conditional_generator.ipynb",
         "generate_feasible_design_mask_jvp": "05_conditional_generator.ipynb",
         "mse": "06_optimization.ipynb",
         "huber_loss": "06_optimization.ipynb"}

modules = ["utils.py",
           "brushes.py",
           "design.py",
           "touching.py",
           "conditional_generator.py",
           "optimization.py"]

doc_url = "https://flaport.github.io/inverse_design/"

git_url = "https://github.com/flaport/inverse_design/tree/master"

def custom_doc_links(name): return None
