# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"new_design": "02_algorithm.ipynb",
         "new_tsb": "00_core.ipynb",
         "new_tvb": "00_core.ipynb",
         "is_complete": "00_core.ipynb",
         "fill_solid": "00_core.ipynb",
         "fill_void": "00_core.ipynb",
         "random_touch": "00_core.ipynb",
         "conv2d": "01_utils.ipynb",
         "batch_conv2d": "01_utils.ipynb",
         "dilute": "01_utils.ipynb",
         "UNASSIGNED": "02_algorithm.ipynb",
         "VOID": "02_algorithm.ipynb",
         "SOLID": "02_algorithm.ipynb",
         "PIXEL_IMPOSSIBLE": "02_algorithm.ipynb",
         "PIXEL_EXISTING": "02_algorithm.ipynb",
         "PIXEL_POSSIBLE": "02_algorithm.ipynb",
         "PIXEL_REQUIRED": "02_algorithm.ipynb",
         "TOUCH_REQUIRED": "02_algorithm.ipynb",
         "TOUCH_INVALID": "02_algorithm.ipynb",
         "TOUCH_EXISTING": "02_algorithm.ipynb",
         "TOUCH_VALID": "02_algorithm.ipynb",
         "TOUCH_FREE": "02_algorithm.ipynb",
         "TOUCH_RESOLVING": "02_algorithm.ipynb",
         "Design": "02_algorithm.ipynb",
         "circular_brush": "02_algorithm.ipynb",
         "notched_square_brush": "02_algorithm.ipynb",
         "show_mask": "02_algorithm.ipynb",
         "visualize": "02_algorithm.ipynb",
         "add_void_touch": "02_algorithm.ipynb",
         "take_free_void_touches": "02_algorithm.ipynb"}

modules = ["core.py",
           "utils.py",
           "algorithm.py"]

doc_url = "https://flaport.github.io/inverse_design/"

git_url = "https://github.com/flaport/inverse_design/tree/master"

def custom_doc_links(name): return None
