# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"new_design": "01_algorithm.ipynb",
         "new_tsb": "00_core.ipynb",
         "new_tvb": "00_core.ipynb",
         "is_complete": "00_core.ipynb",
         "fill_solid": "00_core.ipynb",
         "fill_void": "00_core.ipynb",
         "random_touch": "00_core.ipynb",
         "UNASSIGNED": "01_algorithm.ipynb",
         "VOID": "01_algorithm.ipynb",
         "SOLID": "01_algorithm.ipynb",
         "PIXEL_IMPOSSIBLE": "01_algorithm.ipynb",
         "PIXEL_EXISTING": "01_algorithm.ipynb",
         "PIXEL_POSSIBLE": "01_algorithm.ipynb",
         "PIXEL_REQUIRED": "01_algorithm.ipynb",
         "TOUCH_REQUIRED": "01_algorithm.ipynb",
         "TOUCH_INVALID": "01_algorithm.ipynb",
         "TOUCH_EXISTING": "01_algorithm.ipynb",
         "TOUCH_VALID": "01_algorithm.ipynb",
         "TOUCH_FREE": "01_algorithm.ipynb",
         "TOUCH_RESOLVING": "01_algorithm.ipynb",
         "Design": "01_algorithm.ipynb",
         "circular_brush": "01_algorithm.ipynb",
         "visualize": "01_algorithm.ipynb",
         "design": "01_algorithm.ipynb",
         "add_void_touch": "01_algorithm.ipynb"}

modules = ["core.py",
           "algorithm.py"]

doc_url = "https://flaport.github.io/inverse_design/"

git_url = "https://github.com/flaport/inverse_design/tree/master"

def custom_doc_links(name): return None
