# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/00_core.ipynb (unless otherwise specified).

__all__ = ['new_design', 'new_tsb', 'new_tvb', 'is_complete', 'fill_solid', 'fill_void', 'random_touch']

# Internal Cell
import jax.numpy as jnp

# Cell
def new_design():
    return jnp.zeros([6, 8], dtype=jnp.int8)

# Cell
def new_tsb():
    return []

# Cell
def new_tvb():
    return []

# Cell
def is_complete(design):
    return (jnp.abs(design) == 1).all()

# Cell
def fill_solid(design):
    return design.at[:,:].set(1)

# Cell
def fill_void(design):
    return design.at[:,:].set(-1)

# Cell
def random_touch(design):
    pass