# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/05_direct_optimization.ipynb (unless otherwise specified).

__all__ = ['mse', 'huber_loss']

# Cell
import jax
from .brushes import notched_square_brush
from .conditional_generator import (
    generate_feasible_design_mask,
    new_latent_design,
    transform,
)
from jax.example_libraries.optimizers import adam
from tqdm.notebook import trange

# Cell
def mse(x, y) -> float:
    return ((x - y) ** 2).mean()

# Cell
def huber_loss(x, y, delta=0.5) -> float:
    return ((delta**2) * ((1.0 + ((x - y) / delta) ** 2) ** 0.5 - 1.0)).mean()