# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/03_forward.ipynb (unless otherwise specified).

__all__ = []

# Cell
import jax
import jax.numpy as jnp
import numpy as np
from .utils import conv2d, randn
from .generator import (
    new_design,
    add_void_touch,
    take_free_void_touches,
    add_solid_touch,
    take_free_solid_touches,
)
from itertools import count
from .generator import (
    UNASSIGNED,
    VOID,
    SOLID,
    PIXEL_IMPOSSIBLE,
    PIXEL_EXISTING,
    PIXEL_POSSIBLE,
    PIXEL_REQUIRED,
    TOUCH_REQUIRED,
    TOUCH_INVALID,
    TOUCH_EXISTING,
    TOUCH_VALID,
    TOUCH_FREE,
    TOUCH_RESOLVING,
)