# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/10_inverse_design_local.ipynb.

# %% auto 0
__all__ = []

# %% ../notebooks/10_inverse_design_local.ipynb 2
from inverse_design.inverse_design import *
from inverse_design.brushes import notched_square_brush
from inverse_design.naive_inverse_design import (
    viz_sim, mode_overlap, mask_combine_epsr
)
from inverse_design.conditional_generator import (
    new_latent_design, transform
)
from tqdm.notebook import trange
from jax.example_libraries.optimizers import adam

# %% ../notebooks/10_inverse_design_local.ipynb 3
import jax
import jax.numpy as jnp
from javiche import jaxit
import matplotlib.pylab as plt
import numpy as np
from inverse_design.local_generator import generate_feasible_design_mask
