# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/10_inverse_design_local.ipynb (unless otherwise specified).

__all__ = []

# Internal Cell

from .inverse_design import *
from .brushes import notched_square_brush
from .naive_inverse_design import (
    viz_sim, mode_overlap, mask_combine_epsr, init_domain
)
from .conditional_generator import (
    new_latent_design, transform
)
from tqdm.notebook import trange
from jax.example_libraries.optimizers import adam
from ceviche.modes import insert_mode

# Internal Cell

import jax
import jax.numpy as jnp
from javiche import jaxit
import matplotlib.pylab as plt
import numpy as np
from .local_generator import generate_feasible_design_mask