# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/06_naive_inverse_design.ipynb (unless otherwise specified).

__all__ = []

# Internal Cell
import collections

import autograd.numpy as npa
import ceviche
import numpy as np
import matplotlib.pylab as plt
from ceviche import fdfd_ez, jacobian
from ceviche.modes import insert_mode
from jax.example_libraries.optimizers import adam
from tqdm.notebook import trange

Slice = collections.namedtuple('Slice', 'x y')