# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/04_optimization.ipynb (unless otherwise specified).

__all__ = ['mse', 'huber_loss']

# Cell
import jax
import jax.numpy as jnp
import numpy as np
from .forward import (
    generate_feasible_design,
    new_latent_design,
    transform,
)
from .generator import SOLID, notched_square_brush
from jax.example_libraries.optimizers import adam
from tqdm.notebook import trange

# Cell
def mse(x, y) -> float:
    return ((x - y) ** 2).mean()

# Cell
def huber_loss(x, y, delta=0.5) -> float:
    return ((delta**2) * ((1.0 + ((x - y) / delta) ** 2) ** 0.5 - 1.0)).mean()