name: main
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - actions
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/main.yml"
      - "docs/**"
      - "*.md"
      - ".git*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy, cargo
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install git+https://github.com/fancompute/ceviche
      - name: Build Rust Dependency
        run: |
          cd rust && cargo build --release && cd -
          cp rust/target/release/libinverse_design_rs.so inverse_design_rs.so
          cp rust/target/release/libinverse_design_rs.so notebooks/inverse_design_rs.so
          python -c "import inverse_design_rs" && echo "root: rust library found!"
          cd notebooks && python -c "import inverse_design_rs" && echo "notebooks: rust library found!" && cd -
      - name: Run notebooks
        run: python run_notebooks.py
      - name: Convert to docs
        run: nbdev_docs
      - name: Expose 'notebooks' as artifact
        uses: actions/upload-artifact@master
        with:
          name: notebooks
          path: notebooks
      - name: Expose 'index.ipynb' as artifact
        uses: actions/upload-artifact@master
        with:
          name: index.ipynb
          path: index.ipynb
      - name: Expose '_docs' as artifact
        uses: actions/upload-artifact@master
        with:
          name: _docs
          path: _docs

  pages:
    runs-on: ubuntu-latest
    needs:
      - run
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download '_docs' artifact
        uses: actions/download-artifact@master
        with:
          name: _docs
          path: _docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: pages
          folder: _docs
