name: main
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - actions
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/main.yml"
      - "docs/**"
      - "*.md"
      - ".git*"

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: condaforge/mambaforge
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: mamba env update -n base
      - name: Run notebooks
        run: python run_notebooks.py
      - name: Convert to docs
        run: nbdev_docs
      - name: Expose 'notebooks' as artifact
        uses: actions/upload-artifact@master
        with:
          name: notebooks
          path: /github/workspace/notebooks
      - name: Expose 'index.ipynb' as artifact
        uses: actions/upload-artifact@master
        with:
          name: index.ipynb
          path: /github/workspace/index.ipynb
      - name: Expose '_docs' as artifact
        uses: actions/upload-artifact@master
        with:
          name: _docs
          path: /github/workspace/_docs

  pages:
    runs-on: ubuntu-latest
    needs:
      - run
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download '_docs' artifact
        uses: actions/download-artifact@master
        with:
          name: _docs
          path: _docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: pages
          folder: _docs
